name: story_app_dicoding
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.0-72.0.dev <4.0.0"

dependencies:
  dio: ^5.3.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_feather_icons: ^2.0.0+1
  flutter_hooks: ^0.20.0
  get_it: ^7.6.0
  google_fonts: ^5.1.0
  image_picker: ^1.0.2
  intl: ^0.18.1
  retrofit: ^4.0.1
  shared_preferences: ^2.2.0
  timeago: ^3.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  retrofit_generator: ^7.0.8
  build_runner: ^2.4.6

flutter:
  uses-material-design: true

  assets:
    - lib/core/assets/images/
